import { GraphQLIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import type { GraphQLRequestResponse } from '@/tools/graphql/types'

export const GraphQLBlock: BlockConfig<GraphQLRequestResponse> = {
  type: 'graphql',
  name: 'GraphQL',
  description: 'Send a GraphQL query or mutation to any GraphQL endpoint.',
  longDescription:
    'Use the GraphQL block to send queries and mutations to any GraphQL API. Supports custom headers, query parameters, variables, proxy routing, and configurable timeouts.',
  category: 'tools',
  bgColor: '#E535AB',
  icon: GraphQLIcon,
  subBlocks: [
    {
      id: 'method',
      title: 'Method',
      type: 'dropdown',
      required: true,
      options: [
        { label: 'POST', id: 'POST' },
        { label: 'GET', id: 'GET' },
        { label: 'PUT', id: 'PUT' },
        { label: 'PATCH', id: 'PATCH' },
        { label: 'DELETE', id: 'DELETE' },
        { label: 'HEAD', id: 'HEAD' },
      ],
      value: () => 'POST',
    },
    {
      id: 'url',
      title: 'URL',
      type: 'short-input',
      placeholder: 'https://api.example.com/graphql',
      required: true,
    },
    {
      id: 'params',
      title: 'Query Params',
      type: 'table',
      columns: ['Key', 'Value'],
    },
    {
      id: 'headers',
      title: 'Headers',
      type: 'table',
      columns: ['Key', 'Value'],
    },
    {
      id: 'query',
      title: 'Query',
      type: 'code',
      language: 'javascript',
      placeholder: 'query { ... }',
      required: true,
    },
    {
      id: 'variables',
      title: 'Variables',
      type: 'code',
      language: 'json',
      placeholder: '{ "key": "value" }',
    },
    {
      id: 'useProxy',
      title: 'Use Proxy',
      type: 'switch',
      tooltip: 'Use a proxy for this request',
    },
    {
      id: 'proxyHost',
      title: 'Proxy Host',
      type: 'short-input',
      placeholder: 'proxy.example.com',
      required: true,
      condition: { field: 'useProxy', value: true },
    },
    {
      id: 'proxyPort',
      title: 'Proxy Port',
      type: 'short-input',
      placeholder: '8080',
      required: true,
      condition: { field: 'useProxy', value: true },
    },
    {
      id: 'proxyUsername',
      title: 'Proxy Username',
      type: 'short-input',
      placeholder: 'username',
      condition: { field: 'useProxy', value: true },
    },
    {
      id: 'proxyPassword',
      title: 'Proxy Password',
      type: 'short-input',
      placeholder: 'password',
      password: true,
      condition: { field: 'useProxy', value: true },
    },
    {
      id: 'timeout',
      title: 'Timeout (milliseconds)',
      type: 'short-input',
      placeholder: '30',
    },
  ],
  tools: {
    access: ['graphql_request'],
    config: {
      tool: () => 'graphql_request',
    },
  },
  inputs: {
    method: { type: 'string', description: 'HTTP method' },
    url: { type: 'string', description: 'The GraphQL endpoint URL' },
    params: { type: 'json', description: 'URL query parameters as key-value pairs' },
    headers: { type: 'json', description: 'HTTP headers as key-value pairs' },
    query: { type: 'string', description: 'The GraphQL query or mutation document' },
    variables: { type: 'string', description: 'JSON-encoded GraphQL variables' },
    useProxy: { type: 'boolean', description: 'Whether to route through a proxy server' },
    proxyHost: { type: 'string', description: 'Proxy server hostname or IP address' },
    proxyPort: { type: 'string', description: 'Proxy server port number' },
    proxyUsername: { type: 'string', description: 'Proxy authentication username' },
    proxyPassword: { type: 'string', description: 'Proxy authentication password' },
    timeout: { type: 'number', description: 'Request timeout in milliseconds' },
  },
  outputs: {
    data: { type: 'json', description: 'The data field from the GraphQL response' },
    errors: { type: 'json', description: 'GraphQL errors returned by the server, if any' },
    status: { type: 'number', description: 'HTTP status code of the response' },
    headers: { type: 'json', description: 'Response headers as key-value pairs' },
  },
}
